// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCMVtlCufu_agl_JzIF3PclnCTJljLFUc',
    appId: '1:636037073970:web:48a76ba75fee40512fc02b',
    messagingSenderId: '636037073970',
    projectId: 'koda-80dc1',
    authDomain: 'koda-80dc1.firebaseapp.com',
    storageBucket: 'koda-80dc1.appspot.com',
    measurementId: 'G-DZWJZ5PM4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSuPeEAptpCZggE29FtiZIr2WSNPwlQIs',
    appId: '1:636037073970:android:8e5e949ab464ea162fc02b',
    messagingSenderId: '636037073970',
    projectId: 'koda-80dc1',
    storageBucket: 'koda-80dc1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcaP7F7uqZ-dyI01xRcyN24Wr4z1T0FUs',
    appId: '1:636037073970:ios:04fe9df98bdc47332fc02b',
    messagingSenderId: '636037073970',
    projectId: 'koda-80dc1',
    storageBucket: 'koda-80dc1.appspot.com',
    iosClientId: '636037073970-r7ii91rltkhrjf40sn9lknm8dsf4j483.apps.googleusercontent.com',
    iosBundleId: 'com.example.koda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcaP7F7uqZ-dyI01xRcyN24Wr4z1T0FUs',
    appId: '1:636037073970:ios:04fe9df98bdc47332fc02b',
    messagingSenderId: '636037073970',
    projectId: 'koda-80dc1',
    storageBucket: 'koda-80dc1.appspot.com',
    iosClientId: '636037073970-r7ii91rltkhrjf40sn9lknm8dsf4j483.apps.googleusercontent.com',
    iosBundleId: 'com.example.koda',
  );
}
